### PR TITLE
NetworkMembersip.nominate working

### PR DESCRIPTION
**Pull request by kartikaysaxena**
Added till some parts of DID Module, test script not working because of a [upstream issue](https://github.com/centrifuge/go-substrate-rpc-client/issues/386) in `go-substrate-rpc-client` due to which not able to submit an extrinsic as it throws error 
```
submit_extrinsic_test.go:76: extrinsic submit failed: Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
        WASM backtrace:
        error while executing at wasm backtrace:
            0: 0x71d10 - <unknown>!rust_begin_unwind
            1: 0xc920 - <unknown>!core::panicking::panic_fmt::h7d22643b0becf577
            2: 0x25f601 - <unknown>!TaggedTransactionQueue_validate_transaction
```
Added README for basic setup

*EDIT* Relevant demo script working

### CODE REVIEW

**Comment by vatsa287** [comment]
@kartikaysaxena 
You can stash the non-working bits for now, or keep it in you origin. 
Amend until working bits so it can be pushed.

**Comment by kartikaysaxena** [comment]
[like]  Kartikay reacted to your message:
________________________________

**Review by vatsa287 — DISMISSED** [review]

**Comment by vatsa287** [comment]
@kartikaysaxena There is conflicts. Mainly about Readme. Please update it.

**Comment by kartikaysaxena** [comment]
Fixed in #11

**Pull request closed without merging**
